apiVersion: v1
kind: Service
metadata:
  name: rancher-monitoring-prometheus
spec:
  ports:
    - name: http
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: rancher-monitoring
    app.kubernetes.io/name: prometheus
  sessionAffinity: None
  type: ClusterIP
