defaultNamespace: istio-system
name: grafana

helm:
  releaseName: grafana
  version: 9.2.10
  chart: oci://dp.apps.rancher.io/charts/grafana
  values:
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
        - name: Prometheus
          type: prometheus
          url: http://prometheus-server
          access: proxy
          isDefault: true
          editable: false
    dashboards:
      default:
        istio-mesh-dashboard:
          gnetId: 7639
          revision: 262
        istio-service-dashboard:
          gnetId: 7636
          revision: 262
        istio-workload-dashboard:
          gnetId: 7630
          revision: 262
        istio-performance-dashboard:
          gnetId: 11829
          revision: 262
        istio-control-plane-dashboard:
          gnetId: 7645
          revision: 262

labels:
  app: grafana

# https://rancher.giebert.dev/k8s/clusters/c-m-qf2m8k7c/api/v1/namespaces/istio-system/services/http:grafana:80/proxy/
# rRVX4sltTBCTYK8SlAjTBbL32T35gx0LvbKKGwrb