apiVersion: v1
kind: Service
metadata:
  name: tracing
  namespace: istio-system
spec:
  ports:
    - name: http-query
      port: 16686
      protocol: TCP
      targetPort: 16686
    - name: grpc-query
      port: 16685
      protocol: TCP
      targetPort: 16685
    - name: admin-http
      port: 16687
      protocol: TCP
      targetPort: 16687
  selector:
    app: jaeger
    app.kubernetes.io/component: all-in-one
    app.kubernetes.io/instance: tracing
    app.kubernetes.io/managed-by: jaeger-operator
    app.kubernetes.io/name: tracing
    app.kubernetes.io/part-of: jaeger
  sessionAffinity: None
  type: ClusterIP